project:
  type: website
  title: "The 'Cognition Behavior and Ecology' Lab Guide"

website:
  title: "The 'Cognition Behavior and Ecology' Lab Guide"
  page-navigation: true
  
  navbar:
    background: light
    collapse-below: lg
    right:
      - icon: twitter
        href: https://twitter.com/cobe_lab
        aria-label: COBE Lab Twitter
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/cobe-lab/Lab-guide
          - text: Comments
            url:  https://github.com/cobe-lab/Lab-guide/issue

  sidebar:
    style: "docked"
    search: true
    border: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us
      - section: "Lab Environment"
        contents:
          - file: environment/lab_environment.qmd
            text: Lab environment
          - file: environment/code_of_conduct.qmd
            text: Code of conduct
          - file: environment/communication.qmd
            text: Communication
          - file: environment/meetings.qmd
            text: Lab meetings
          - file: environment/mentoring.qmd
            text: Mentoring
          - file: environment/work_life_balance.qmd
            text: Work/life balance
          - file: environment/working_remotely.qmd
            text: Working remotely
      - href: funding/funding.qmd
        text: Funding and jobs
      - section: "Publications"
        contents:
          - href: publication/addressing_errors.qmd
            text: Addressing errors
          - href: publication/authorship.qmd
            text: Authorship
          - href: publication/conferences.qmd
            text: Conferences
          - href: publication/openaccess.qmd
            text: Open Access 
          - href: publication/public_engagement.qmd
            text: Public engagement
      - section: "Research"
        # contents:
         # - href: copilot.qmd
         #   text: Copilot system
         # - href: rdm.qmd
         #   text: Data Managment
         # - href: extern.qmd
         #   text: External partners
         # - href: facilities.qmd
         #   text: Facilities
         # - href: ip.qmd
         #   text: Intellectual Property
         # - href: preg.qmd
         #   text: Preregistration 
         # - href: support.qmd
         #   text: Support
        
          
  page-footer: This guide is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


